[package]
name = "turko"
description = "."
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"

[profile.release]
debug = true

[dependencies]
phf = "0.11.2"

[build-dependencies]
phf = "0.11.2"
phf_codegen = "0.11.2"
